name: Build s2-lite

on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to checkout"
        required: false
        type: string
        default: "main"
      artifact-name:
        description: "Name for the uploaded artifact"
        required: false
        type: string
        default: "server-binary"
      binary-name:
        description: "Name of the binary in the artifact"
        required: false
        type: string
        default: "server"
      retention-days:
        description: "Number of days to retain the artifact"
        required: false
        type: number
        default: 1
      runner:
        description: "Runner to use"
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  build:
    name: Build s2-lite
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: s2-streamstore/s2
          ref: ${{ inputs.ref }}
          submodules: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Setup Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build s2-lite
        run: cargo build --release -p s2-lite

      - name: Upload binary
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ inputs.artifact-name }}
          path: target/release/${{ inputs.binary-name }}
          retention-days: ${{ inputs.retention-days }}
